import type { AccountingEntry, Invoice, Payment, Refund } from '../auth/types'
import { uid } from '../data/store'

const ACCOUNTS = {
  clients: { code: '411', label: 'Clients' },
  bank: { code: '512', label: 'Banque' },
  revenue: { code: '706', label: 'Prestations de services' },
  vat: { code: '44571', label: 'TVA collectée' },
} as const

function entry(
  partial: Omit<AccountingEntry, 'id' | 'autoGenerated'>,
): AccountingEntry {
  return { ...partial, id: uid('acc'), autoGenerated: true }
}

export function entriesForInvoiceSent(invoice: Invoice): AccountingEntry[] {
  const ref = invoice.number
  const date = invoice.sentAt ?? invoice.createdAt
  return [
    entry({
      date,
      label: `Facture ${ref} · ${invoice.clientName}`,
      type: 'receivable',
      accountCode: ACCOUNTS.clients.code,
      accountLabel: ACCOUNTS.clients.label,
      debit: invoice.totalTTC,
      credit: 0,
      reference: ref,
      invoiceId: invoice.id,
      userId: invoice.userId,
    }),
    entry({
      date,
      label: `Facture ${ref} · vente HT`,
      type: 'revenue',
      accountCode: ACCOUNTS.revenue.code,
      accountLabel: ACCOUNTS.revenue.label,
      debit: 0,
      credit: invoice.totalHT,
      reference: ref,
      invoiceId: invoice.id,
      userId: invoice.userId,
    }),
    entry({
      date,
      label: `Facture ${ref} · TVA`,
      type: 'vat_collected',
      accountCode: ACCOUNTS.vat.code,
      accountLabel: ACCOUNTS.vat.label,
      debit: 0,
      credit: invoice.totalTVA,
      reference: ref,
      invoiceId: invoice.id,
      userId: invoice.userId,
    }),
  ]
}

export function entriesForPayment(payment: Payment, invoice: Invoice): AccountingEntry[] {
  const date = payment.completedAt ?? payment.createdAt
  return [
    entry({
      date,
      label: `Encaissement ${payment.reference}`,
      type: 'payment',
      accountCode: ACCOUNTS.bank.code,
      accountLabel: ACCOUNTS.bank.label,
      debit: payment.amount,
      credit: 0,
      reference: payment.reference,
      invoiceId: invoice.id,
      paymentId: payment.id,
      userId: payment.userId,
    }),
    entry({
      date,
      label: `Règlement facture ${invoice.number}`,
      type: 'receivable',
      accountCode: ACCOUNTS.clients.code,
      accountLabel: ACCOUNTS.clients.label,
      debit: 0,
      credit: payment.amount,
      reference: payment.reference,
      invoiceId: invoice.id,
      paymentId: payment.id,
      userId: payment.userId,
    }),
  ]
}

export function entriesForRefund(refund: Refund, payment: Payment, invoice: Invoice): AccountingEntry[] {
  const date = refund.completedAt ?? refund.createdAt
  const ref = `REM-${refund.id.slice(-6).toUpperCase()}`
  return [
    entry({
      date,
      label: `Remboursement · ${refund.reason}`,
      type: 'refund',
      accountCode: ACCOUNTS.clients.code,
      accountLabel: ACCOUNTS.clients.label,
      debit: refund.amount,
      credit: 0,
      reference: ref,
      invoiceId: invoice.id,
      paymentId: payment.id,
      refundId: refund.id,
      userId: refund.userId,
    }),
    entry({
      date,
      label: `Remboursement banque · ${ref}`,
      type: 'refund',
      accountCode: ACCOUNTS.bank.code,
      accountLabel: ACCOUNTS.bank.label,
      debit: 0,
      credit: refund.amount,
      reference: ref,
      invoiceId: invoice.id,
      paymentId: payment.id,
      refundId: refund.id,
      userId: refund.userId,
    }),
  ]
}

export function summarizeLedger(entries: AccountingEntry[]) {
  const totalDebit = entries.reduce((s, e) => s + e.debit, 0)
  const totalCredit = entries.reduce((s, e) => s + e.credit, 0)
  const revenue = entries
    .filter((e) => e.type === 'revenue')
    .reduce((s, e) => s + e.credit, 0)
  const vat = entries
    .filter((e) => e.type === 'vat_collected')
    .reduce((s, e) => s + e.credit, 0)
  return { totalDebit, totalCredit, revenue, vat, balanced: Math.abs(totalDebit - totalCredit) < 0.01 }
}
